/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth.module';
import * as i2 from './singin.component.ngfactory';
import * as i3 from './signup.component.ngfactory';
import * as i4 from './logout.component.ngfactory';
import * as i5 from '@angular/forms';
import * as i6 from '@angular/common';
import * as i7 from '@angular/router';
import * as i8 from './singin.component';
import * as i9 from './signup.component';
import * as i10 from './logout.component';
export const AuthModuleNgFactory:i0.NgModuleFactory<i1.AuthModule> = i0.ɵcmf(i1.AuthModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SigninComponentNgFactory,i3.SignupComponentNgFactory,i4.LogoutComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.FormBuilder,
          i5.FormBuilder,([] as any[])),i0.ɵmpd(4608,i5.ɵi,i5.ɵi,([] as any[])),i0.ɵmpd(4608,
          i6.NgLocalization,i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i5.ɵba,
          i5.ɵba,([] as any[])),i0.ɵmpd(512,i5.ReactiveFormsModule,i5.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,([] as any[])),
          i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,[[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,
              i1.AuthModule,i1.AuthModule,([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',redirectTo:'signup',pathMatch:'full'},{path:'signin',
                component:i8.SigninComponent},{path:'signup',component:i9.SignupComponent},
                {path:'logout',component:i10.LogoutComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRzovQ1NDSV9JVS9NRUFOL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRzovQ1NDSV9JVS9NRUFOL3NlZWQtcHJvamVjdC9hc3NldHMvYXBwL2F1dGgvYXV0aC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
